Class ETPKG.NewClass1 Extends %Persistent
{

Storage Default
{
<Data name="NewClass1DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^ETPKG.NewClass1D</DataLocation>
<DefaultData>NewClass1DefaultData</DefaultData>
<IdLocation>^ETPKG.NewClass1D</IdLocation>
<IndexLocation>^ETPKG.NewClass1I</IndexLocation>
<StreamLocation>^ETPKG.NewClass1S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
